spring:
  application:
    name: document-and-author-management
  datasource:
    url: jdbc:postgresql://localhost:5434/document_and_author_db
    username: krieger
    password: krieger
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "initializing all possible tables in document_and_author_db."
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  api-docs:
    path: /api-docs
server:
  port: 9090
