spring:
  application:
    name: document-and-author-management
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:document_and_author_db}"
    username: ${DB_USER:krieger}
    password: ${DB_PASSWORD:krieger}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "initializing all possible tables in document_and_author_db."
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  api-docs:
    path: /api-docs
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: document-and-author-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: com.krieger.author.models
kafka:
  topic: document-and-author-topic
server:
  port: 9090
basic:
  auth:
    document:
      username: krieger-document
      password: krieger-document
      role: DOCUMENT
    author:
      username: krieger-author
      password: krieger-author
      role: AUTHOR
logging:
  level:
    root: INFO
    com:
      krieger: INFO # for detailed log on entire application, please enable to DEBUG.
    org:
      hibernate: ERROR
